version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - qa-bot-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["streamlit", "run", "/app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8501:8501"
    networks:
      - qa-bot-network

networks:
  qa-bot-network:
    driver: bridge
